# FIRST_HALF: 상반기 주문 정보
## SHIPMENT_ID: 출하 번호
## FLAVOR(PK): 맛
## TOTAL_ORDER: 총주문량

# ICECREAM_INFO: 성분 정보
## FLAVOR(FK): 맛
## INGREDIENT_TYPE: 성분 타입

# 1. 상반기 총주문량 3000 초과
# 2. 주성분은 과일
# 3. 총주문량이 큰 순서대로, DESC

# FIRST_HALF 테이블에서 TOTAL_ORDER가 3000 초과
# ICECREAM_INFO 테이블에서 INGREDIENT_TYPE이 fruit_based
# TOTAL_ORDER의 값이 큰 순서대로 DESC
# FLAVOR는 FIRST_HALF의 외래키

SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF INNER JOIN ICECREAM_INFO
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER > 3000 
AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC